apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: junebot
  name: junebot
  namespace: dsuurlant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: junebot
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: junebot
    spec:
      containers:
        - env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  key: NODE_ENV
                  name: junebot-config-98ta
            - name: DISCORD_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: DISCORD_TOKEN
                  name: junebot-config-98ta
            - name: CAT_API_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: CAT_API_TOKEN
                  name: junebot-config-98ta
            - name: CAT_API_URL
              valueFrom:
                configMapKeyRef:
                  key: CAT_API_URL
                  name: junebot-config-98ta
            - name: DOG_API_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: DOG_API_TOKEN
                  name: junebot-config-98ta
            - name: DOG_API_URL
              valueFrom:
                configMapKeyRef:
                  key: DOG_API_URL
                  name: junebot-config-98ta
          image: gcr.io/central-accord-297810/github.com/dsuurlant/junebot
          imagePullPolicy: IfNotPresent
          name: junebot-1
